# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build project
          command: npm run build
  test:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
  eslint:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run ESLint
          command: npm run lint
  test_e2e:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run E2E tests
          command: npm run test:e2e

workflows:
  Build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
  Test:
    jobs:
      - test
  ESLint:
    jobs:
      - eslint
  E2E:
    jobs:
      - test_e2e
